package report

import (
	"bytes"
	"fmt"
	"time"

	"secscan/models"

	"github.com/jung-kurt/gofpdf"
)

// GeneratePDF — tarama sonuçlarından PDF rapor oluştur
func GeneratePDF(result *models.ScanResult) ([]byte, error) {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.SetAutoPageBreak(true, 20)

	// Sayfa 1 — Kapak
	pdf.AddPage()

	// Header
	pdf.SetFillColor(13, 17, 23)
	pdf.Rect(0, 0, 210, 60, "F")
	pdf.SetTextColor(88, 166, 255)
	pdf.SetFont("Helvetica", "B", 28)
	pdf.SetXY(15, 15)
	pdf.Cell(180, 15, "SecScan Security Report")

	pdf.SetTextColor(201, 209, 217)
	pdf.SetFont("Helvetica", "", 12)
	pdf.SetXY(15, 35)
	pdf.Cell(180, 8, fmt.Sprintf("Target: %s", result.URL))
	pdf.SetXY(15, 45)
	pdf.Cell(180, 8, fmt.Sprintf("Date: %s", result.StartTime.Format("2006-01-02 15:04:05")))

	// Skor kutusu
	pdf.SetXY(15, 70)
	gradeColor := getGradeColor(result.Grade)
	pdf.SetFillColor(gradeColor[0], gradeColor[1], gradeColor[2])
	pdf.SetTextColor(255, 255, 255)
	pdf.SetFont("Helvetica", "B", 48)
	pdf.CellFormat(50, 50, result.Grade, "0", 0, "C", true, 0, "")

	pdf.SetTextColor(13, 17, 23)
	pdf.SetFont("Helvetica", "B", 18)
	pdf.SetXY(75, 75)
	pdf.Cell(120, 10, fmt.Sprintf("Security Score: %d/100", result.Score))

	pdf.SetFont("Helvetica", "", 12)
	pdf.SetXY(75, 90)
	scanDuration := "N/A"
	if result.EndTime != nil {
		scanDuration = result.EndTime.Sub(result.StartTime).Round(time.Millisecond).String()
	}
	pdf.Cell(120, 8, fmt.Sprintf("Scan Duration: %s", scanDuration))
	pdf.SetXY(75, 100)
	pdf.Cell(120, 8, fmt.Sprintf("Total Findings: %d", len(result.Findings)))

	// Özet tablo
	pdf.SetXY(15, 130)
	pdf.SetFont("Helvetica", "B", 14)
	pdf.SetTextColor(13, 17, 23)
	pdf.Cell(180, 10, "Summary by Severity")
	pdf.Ln(15)

	severityCounts := map[string]int{"critical": 0, "high": 0, "medium": 0, "low": 0, "info": 0}
	for _, f := range result.Findings {
		severityCounts[f.Severity]++
	}

	// Severity tablosu
	pdf.SetFont("Helvetica", "B", 11)
	headers := []string{"Severity", "Count"}
	widths := []float64{90, 90}

	pdf.SetFillColor(30, 30, 30)
	pdf.SetTextColor(255, 255, 255)
	for i, h := range headers {
		pdf.CellFormat(widths[i], 10, h, "1", 0, "C", true, 0, "")
	}
	pdf.Ln(-1)

	pdf.SetFont("Helvetica", "", 11)
	severityOrder := []string{"critical", "high", "medium", "low", "info"}
	severityLabels := map[string]string{
		"critical": "CRITICAL",
		"high":     "HIGH",
		"medium":   "MEDIUM",
		"low":      "LOW",
		"info":     "INFO",
	}

	for _, sev := range severityOrder {
		count := severityCounts[sev]
		colors := getSeverityColor(sev)
		pdf.SetFillColor(colors[0], colors[1], colors[2])
		pdf.SetTextColor(255, 255, 255)
		pdf.CellFormat(widths[0], 8, severityLabels[sev], "1", 0, "C", true, 0, "")
		pdf.SetFillColor(245, 245, 245)
		pdf.SetTextColor(13, 17, 23)
		pdf.CellFormat(widths[1], 8, fmt.Sprintf("%d", count), "1", 0, "C", true, 0, "")
		pdf.Ln(-1)
	}

	// Sayfa 2+ — Modül sonuçları
	for _, mod := range result.ModuleResults {
		pdf.AddPage()

		// Modül başlığı
		pdf.SetFont("Helvetica", "B", 16)
		pdf.SetTextColor(88, 166, 255)
		pdf.Cell(180, 12, mod.Name)
		pdf.Ln(8)

		pdf.SetFont("Helvetica", "", 10)
		pdf.SetTextColor(100, 100, 100)
		pdf.Cell(90, 8, fmt.Sprintf("Score: %d/100", mod.Score))
		pdf.Cell(90, 8, fmt.Sprintf("Duration: %.0fms", mod.Duration))
		pdf.Ln(12)

		if len(mod.Findings) == 0 {
			pdf.SetFont("Helvetica", "I", 11)
			pdf.SetTextColor(63, 185, 80)
			pdf.Cell(180, 8, "No vulnerabilities found!")
			continue
		}

		// Bulgular
		for i, f := range mod.Findings {
			// Yeni sayfa kontrolü
			if pdf.GetY() > 250 {
				pdf.AddPage()
			}

			colors := getSeverityColor(f.Severity)
			pdf.SetFillColor(colors[0], colors[1], colors[2])
			pdf.SetTextColor(255, 255, 255)
			pdf.SetFont("Helvetica", "B", 9)
			pdf.CellFormat(20, 7, fmt.Sprintf(" %s ", f.Severity), "0", 0, "C", true, 0, "")

			pdf.SetTextColor(13, 17, 23)
			pdf.SetFont("Helvetica", "B", 10)
			pdf.CellFormat(160, 7, fmt.Sprintf("  %s", f.Title), "0", 0, "L", false, 0, "")
			pdf.Ln(9)

			pdf.SetFont("Helvetica", "", 9)
			pdf.SetTextColor(80, 80, 80)
			pdf.SetX(35)
			pdf.MultiCell(155, 5, f.Detail, "", "L", false)

			if f.Fix != "" {
				pdf.SetX(35)
				pdf.SetTextColor(63, 185, 80)
				pdf.SetFont("Helvetica", "I", 9)
				pdf.MultiCell(155, 5, "Fix: "+f.Fix, "", "L", false)
			}

			if i < len(mod.Findings)-1 {
				pdf.Ln(3)
				pdf.SetDrawColor(220, 220, 220)
				pdf.Line(15, pdf.GetY(), 195, pdf.GetY())
				pdf.Ln(3)
			}
		}
	}

	// Footer — her sayfaya
	totalPages := pdf.PageCount()
	for i := 1; i <= totalPages; i++ {
		pdf.SetPage(i)
		pdf.SetY(-15)
		pdf.SetFont("Helvetica", "I", 8)
		pdf.SetTextColor(150, 150, 150)
		pdf.Cell(90, 8, "Generated by SecScan Security Scanner")
		pdf.Cell(90, 8, fmt.Sprintf("Page %d/%d", i, totalPages))
	}

	var buf bytes.Buffer
	err := pdf.Output(&buf)
	return buf.Bytes(), err
}

func getGradeColor(grade string) [3]int {
	switch grade {
	case "A+", "A":
		return [3]int{63, 185, 80}
	case "B":
		return [3]int{210, 153, 34}
	case "C":
		return [3]int{227, 179, 65}
	case "D":
		return [3]int{219, 109, 40}
	default:
		return [3]int{248, 81, 73}
	}
}

func getSeverityColor(severity string) [3]int {
	switch severity {
	case "critical":
		return [3]int{190, 30, 45}
	case "high":
		return [3]int{248, 81, 73}
	case "medium":
		return [3]int{210, 153, 34}
	case "low":
		return [3]int{88, 166, 255}
	default:
		return [3]int{139, 148, 158}
	}
}
